name: CI

on:
  schedule:
    - cron: "0 7 * * *"

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: guix cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-

      - name: install guix
        uses: PromyLOPh/guix-install-action@v1

      - name: dump package json 
        run: ./build

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
